### ISSUE TITLE
Add unit tests for resolver

### ISSUE THREAD

**Issue by nikneem** [nikneem/shortlink-maintenance-api#5]
Unit test resolver
- Test for valid short code (should redirect to endpoint)
- Test for invalid short code (should redirect to app)
- Test for missing short code (should redirect to app)

**Comment by DillonAd** [comment]
Looks fun! Mind if I take this?

**Comment by nikneem** [comment]
Knock yourself out!

**Comment by nikneem** [comment]
Are you familiar with writing unit tests using Moq? I think you may need to introduce DI to the Resolve project in order to mock the repository out. Good luck!

**Comment by DillonAd** [comment]
I'm fairly familiar with testing with Moq. The only thing that had me worried was the `CloudTable` class, but it looks like people have figured out how to properly mock/fake the necessary behaviors.

**Comment by nikneem** [comment]
Awesome, you can also consider using the factory in the Core project (ICloudTableFactory top of mind) to mock the cloud table fully out of your unit tests.
The Core project is a NuGet package used bij Nuth the maintenance and resolve projects. You can create a startup class for the resolve project (copy from maintenance) and then inject the interface in the resolve function. This makes is way more testable. Just a thought...
